sudo: false
language: python
python:
  - 2.6
  - 2.7
addons:
  apt:
    packages:
      - libtest-exception-perl
      - libtest-output-perl
      - libdevel-cover-perl
      - libmime-lite-perl
      - acl
      - cpanminus
install:
  - export PERL5LIB=~/perl5/lib/perl5
  - pip install coverage
  - cpanm --local-lib=~/perl5 --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
  - git clone --depth=5 https://github.com/salilab/saliweb
  - (cd saliweb && scons modeller_key=UNKNOWN pythondir=$(echo $(dirname $(which python))/../lib/python*/site-packages) perldir=~/perl5/lib/perl5 prefix=~/usr webdir=~/www install)
script:
  - scons coverage=true test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cover -report codecov
