Import('env')

env.InstallHTML(['img/pdf.gif','img/am_logo.gif','img/foxs.gif'],'img')
env.InstallHTML(['file/modeller_scripts.zip','file/Weinkam_PNAS_2012.pdf','file/Weinkam_PNAS_2012_si.pdf','file/input.zip','file/analysis.zip','file/files_glyc.zip','file/input_glyc.zip','file/Schneidman-Duhovny_NucAcRes_2010.pdf','file/restyp.lib','file/demo.zip','file/glyc.dat','file/bonds.dat','file/hemoglobin.pdf'],'file')
