#!/bin/bash
F1=$1

cofm=(`/netapp/sali/allosmod/getcofm $F1`)

awk 'BEGIN{FS=""}($1$2$3$4=="ATOM"){\
{for(a=31;a<=38;a++){printf $a}}{printf " "}\
{for(a=39;a<=46;a++){printf $a}}{printf " "}\
{for(a=47;a<=54;a++){printf $a}}{printf " \n"}}' $F1 |\
awk 'BEGIN{a=0;b=0;c=0}{a+=sqrt(($1-('${cofm[0]}'))^2+($2-('${cofm[1]}'))^2+($3-('${cofm[2]}'))^2)}END{printf "%6.1f\n",a/NR}'

