#!/bin/bash

FIL=$1
dX=`echo "$2/57.2958" | bc -l` #input rotation around each axis in degrees between 0 and 360
dY=`echo "$3/57.2958" | bc -l`
dZ=`echo "$4/57.2958" | bc -l`

if test -z $dZ; then echo "specify dX, dY, and dZ"; exit; fi

#rotate about x axis, then y axis, then z axis
awk 'BEGIN{FS=""}($1$2$3$4=="ATOM"||$1$2$3$4$5$6=="HETATM"){print \
     $31$32$33$34$35$36$37$38" "$39$40$41$42$43$44$45$46" "$47$48$49$50$51$52$53$54" ",$0}' $FIL |\
     awk '{xa=$1;ya=cos('${dX}')*$2-sin('${dX}')*$3;za=sin('${dX}')*$2+cos('${dX}')*$3}\
     {xb=sin('${dY}')*za+cos('${dY}')*xa;yb=ya;zb=cos('${dY}')*za-sin('${dY}')*xa}\
     {xc=cos('${dZ}')*xb-sin('${dZ}')*yb;yc=sin('${dZ}')*xb+cos('${dZ}')*yb;zc=zb}\
     {printf "%8.3f%8.3f%8.3f%s\n",xc,yc,zc,$0}' |\
     awk 'BEGIN{FS=""}{for (a=53;a<=82;a++){printf $a} \
     for (a=1;a<=24;a++){printf $a} \
     for (a=107;a<=NF;a++) {{printf $a}if(a==NF){printf "\n"}}}'
