Import('env')

files = Glob("*")

files = [f for f in files if 'SConscript' not in str(f)]

for d in (env['config'].script_directory, env['config'].script_directory_local):
    i = env.Install(d, files)
    env.Alias('install', i)
    env.Default(i)
