#!/bin/bash

FIL=$1
CHAIN=$2

if test -z $CHAIN; then echo "no chain specified"; exit; fi

awk 'BEGIN{FS=""}($1$2$3$4=="ATOM"||$1$2$3$4$5$6=="HETATM"){for (a=1;a<=21;a++){printf $a} \
     {printf "'${CHAIN}'"}\
     for (a=23;a<=NF;a++) {{printf $a}if(a==NF){printf "\n"}}}' $FIL
