#!/bin/bash

FIL=$1
dX=$2
dY=$3
dZ=$4

if test -z $dZ; then echo "specify dX, dY, and dZ"; exit; fi

awk 'BEGIN{FS=""}($1$2$3$4=="ATOM"||$1$2$3$4$5$6=="HETATM"){print \
     $31$32$33$34$35$36$37$38" "$39$40$41$42$43$44$45$46" "$47$48$49$50$51$52$53$54" ",$0}' $FIL |\
     awk '{printf "%8.3f%8.3f%8.3f%s\n",$1+'${dX}',$2+'${dY}',$3+'${dZ}',$0}' |\
     awk 'BEGIN{FS=""}{for (a=53;a<=82;a++){printf $a} \
     for (a=1;a<=24;a++){printf $a} \
     for (a=107;a<=NF;a++) {{printf $a}if(a==NF){printf "\n"}}}'
