name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.6, 3.7, 3.8, 3.9]
        perl-version: [latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Perl ${{ matrix.perl-version }}
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl-version }}
    - name: Install dependencies
      run: |
        pip install coverage scons flake8
        cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov Test::Exception Test::Output Test::MockModule Devel::Cover MIME::Lite DBI CGI Error
        # Patch Devel::Cover::Report::Codecov to support GitHub Actions
        # from https://github.com/codecov/codecov-perl/pull/41
        reportdir=$(dirname $(perldoc -l Devel::Cover::Report::Codecov) )
        curl https://github.com/codecov/codecov-perl/commit/75ac8c01b3cccbff0acc879467b3952cd9605210.patch > gha.patch && patch -p5 < gha.patch && cp Codecov/Service/GitHub.pm $reportdir/Codecov/Service/GitHub.pm
        git clone --depth=5 https://github.com/salilab/saliweb
        export PYTHON=`pip show coverage |grep Location|cut -b11-`
        (cd saliweb && scons modeller_key=UNKNOWN pythondir=$PYTHON perldir=$PERL5LIB prefix=~/usr webdir=~/www install && touch $PYTHON/saliweb/frontend/config.py)
        rm -rf saliweb
    - name: Test
      run: |
        scons coverage=true python=$(which python) test
        flake8 .
    - name: Upload coverage to codecov
      run: |
        bash <(curl -s https://codecov.io/bash)
        cover -report codecov
